######### Introduction to R #########

# c() is used to concentate whatever is present inside the brackets
# seperated by comma

x <- c(1,3,3,4)   # <- is assignment operator assigning the right side one to left side variable

y=c(1,2,3,4)      # = is also same as <- ,wtf why do people use <- then??

length(x)         # gives a length of a vector ,single dimension vector

length(y)

ls()               # this function is used to list all the objects that we
                   # have saved in workspace so far

rm(x,y)            # rm deletes the variables that we have saved,have to specify inside what to delete

ls()               # Notice that x,y no longer appear

rm(list = ls())    # ls() creates a list of all loaded variables and we assign it to
                   # variable list ,then we ask
                   # rm() to remove everything that is saved
                   # The command listed deletes every variable loaded


########## Matrix ##############

?matrix            # ?function_name is used to see help for that particular function

# lets create a simple matrix
# matrix takes 3 arguments, first is the data itself as a single vector,
# second is number of rows ,third is number of columns
# here z will be = [[1,3],[2,4]] each column is generated first and data is appended columnwise
z=matrix(data= c(1,3,2,4),nrow = 2,ncol = 2)

z

# matrix function can also be written as below,without specifying argument names,
# but the order has to be maintained
z_1 = matrix(c(1,3,2,4),2,2)

z_1

# matrix function has another argument byrow=TRUE which means we populate the matrix
# literally by rows instead of going by columns
# here z will be generated by rows instead of columns as given above
z_2= matrix(c(1,3,2,4),2,2,byrow = TRUE)

z_2

########## Some Vectorized Implementation ##########

sqrt(z)               # often these functions operates on each element in a matrix or
                      # vector or dataframe,no need to use for loop to iterate over

z^2                   # squares every element in a matrix or vector

?rnorm

rnorm(4)              # rnorm creates a random vector or normal variables with given
                      # size defaults= (mean=0 and standard deviation = 1)

rnorm(5,mean=0,sd=4)  # here we are explicitly specifying mean and stadard deviation
                      # for the vector to be created

# sometimes we want our code to reproduce the exact same set of random numbers
# we can use set.seed() function to do this

?set.seed

# lets set the seed to some integer
set.seed(1303)

y=rnorm(5)

mean(y)                # to get the mean of a vector y

mean(z_1)              # mean works on matrices too but it gives mean for all the
                       # elements present in the matrix

var(y)                 # to get the variance of a vector

var(z_1)               # gives a matrix containing variance for each column
                       # say matrix=[[1,2],[3,4]] variance will return [[2,2],[2,2]]

sd(y)                  # standard deviation of a vector y

sd(z_1)                # returns a value over a matrix,same as mean function,it
                       # unwraps all elements in matrix in to single vector and computes for that.



################# Plotting #################

# plot() function is the primary way to plot data in R
# plot(x,y) produces a scatter plot of numbers in x versus numbers in y

# lets initialize x and y and lets plot..

x_forplot = rnorm(100)
y_forplot = rnorm(100)

# basic plot command
plot(x_forplot,y_forplot)

# we can also add arguments for labelling on axis as well as main plot title
plot(x_forplot,y_forplot,xlab = "Xaxis Label here",ylab = "Yaxis Label here",
     main = "Main title label here")

# we also want to save the plots ,the following commands will help in saving in different file formats
pdf("Plotted_figure.pdf")                 # to save in pdf format

jpeg("Plotted_figure.jpeg")

# After initializing the export command to pdf or jpeg then the plot has to called
# it will not take the plots that are already present in the workspace

plot(x_forplot,y_forplot,col="green")

# this following command will say to R that we are done with plot and it can save
# Remember until and unless you initialize this command you cannot
# acces plot function and whatever you are trying to save will not be saved.It will say 0 kb file
dev.off()

# sometimes you want to create a list of numbers for iterating over or couting,
# following function and notation will be helpful
x=seq(1,9)
x                         # both seq and the method below gives the same result
x=1:9
x
# we can also use seq to specify the stepping in between two integers
x=seq(-5,5,length=20)     # here we want 20 equally spaced elements between -5 and 5
                          # and the result vector will be stored in x
x

########### 3D maps an plots #################

# we will create more sophisticated plots.The contour() function produces
#  contour plot to represent 3dimensional data
# it takes x-first dimension,y-second dimension,z-third dimension for a given pair of (x,y) coordinates
# x and y are vectors and z is a array with dimension c(dim(x),dim(y))
?contour

# outer works like this (x,y,f(x,y)) takes x and y as arugument and gives
#  a array with dimension c(dim(x),dim(y)) where each element of array is function of
# specified function as third argument

?outer
x=seq(10)
x
y=seq(10)
z=outer(x,y,function(x,y) cos(y)/(1+x^2))
z
contour(x,y,z)

contour(x,y,z,nlevels = 45,add = TRUE)

# to transpose a matrix or array we can use this
x
t(x)                          # transpose a array or matrix

z_new=(z-t(z))/2

contour(x,y,z_new,nlevels = 15)

# there is another function works same way as contour() is image().
# The difference is that it gives color coded plot whose color depends on z value
# Also known as HeatMaps

?image
image(x,y,z_new)

# we can add particular colors too ; options are rainbow,heat.colors(),topo.colors(),terrain.colors()
image(x,y,z_new,col = heat.colors(20) )
image(x,y,z_new,col = terrain.colors(20))            # These are all different schemas of coloring
image(x,y,z_new,col = rainbow(20))
image(x,y,z_new,col = topo.colors(20))

# Alternatively another function to produce 3D plot is persp()
# Takes two arguments theta and phi apart from x,y,z;
#  Those are angles which control how to view the plot

?persp
persp(x,y,z_new)

# lets view the plot at different angle
persp(x,y,z_new,theta = 30,phi = 40)


############## Indexing Data #################

A=matrix(16:32,4,4)
A

A[2,3]                   # this command selects 2nd row and 3rd column and returns that element

A[c(1,3),c(2,4)]         # this command is selecting 1,3 rows and 2,4 columns and returns a
                         #    2x2 matrix that are intersection of both selected rows and columns

A[1:3,2:4]               # this command selects 1:3--> 1,2,3 rows and 2:4--> 2,3,4 columsn and
                         #    gives the matrix that is intersection of them

A[1:2,]                  # We can leave a blank after , to select all the columns but
                         #    only specified rows

A[,1:2]                  # this command selects all rows but only 1,2 columns,same as
                         #    above but in reverse

A[-2,-3]                 # this command will say that dont select that particular rows and
                         #    columns and return everything else in a matrix or whatever

A[c(-1,-3),c(-2,-4)]     # specifying mutliple columns and rows

A[-c(1,3),-c(2,4)]       # same command as above ,just different notation, "-" can be kept
                         #    outside array too

dim(A)                   # Returns a vector of c(number_of_rows,number_of_columns)



################# Loading Data ##########################

# see what is the working directory first by following command

getwd()

# set the working directory if the data file is in another folder

#setwd("Your directory path where data is")

Auto_data = read.table("data/Auto.data")

dim(Auto_data)

?fix                       # fix(data_object) will open a data editor in new window to
                           #     edit the data in GUI

fix(Auto_data)

# Notice that calling read.table() loaded variable names as part of data in first row
# To avoid that we give another option saying that it has header and add
#     another argument "header=TRUE" in read.table() function

# adds header and will
#   not consider first row as part of data object

Auto_data = read.table("data/Auto.data",header = TRUE)

fix(Auto_data)

dim(Auto_data)             # Notice that dimension has changed from 398 x 9 to 397 x 9

# Sometimes or Most of the times our dataset may have missing values
# To say that data is missing and convey this to R we add another
#     argument " na.strings="?" " in read.table()

Auto_data = read.table("data/Auto.data",header = TRUE,na.strings = "?")

fix(Auto_data)

dim(Auto_data)

typeof(Auto_data)           # read.table() creates a list object

# To load data from csv files we have simple command read.csv()

Auto_data_csv = read.csv("data/Auto.csv",header = T,na.strings = "?")

fix(Auto_data_csv)

dim(Auto_data_csv)

Auto_data_csv[1:4,]

# We can use na.omit() function to simply omit using rows with missing values

Auto_data_csv = na.omit(Auto_data_csv)

dim(Auto_data_csv)            # Notice that we have 5 rows with missing values and those
                              #     are deleted from the data object

typeof(Auto_data_csv)         # read.csv() will generate a list data object ,it is different from matrix

names(Auto_data_csv)          # Whatever the headers we specified ,the feature names can
                              #     be accessed by names(data_object) command


#################### Additional Graphical and Numerical Summaries ############

plot(cylinders,mpg)            # Auto_data_csv object has columns with names cylinders
                               #    and mpg,but we cannot directly access them

# unless we specify them in the following way

plot(Auto_data_csv$cylinders,Auto_data_csv$mpg)        # adding "$" symbol wil let us access
                                                       #    individual columns from the list object

Auto_data_csv[c("cylinders","mpg")]          # another way of accessing individual columns in a list
                                             #  object,   data_object[c(column1_name,column2_name,..)]

# if we are tired of specifying from the data object by explicitly
#     specifying column names inside data object we can use attach()

# attach(data_object) will let us use feature names inside data object,without using $ or like above

attach(Auto_data_csv)           # Notice that we are just simply stating the column name

plot(cylinders,mpg)             # Here inside the plot the names of x and y axes are set to
                                #      feature names

# we can also change the feature types like,from integer to categorical or double,
#     by using the following genre of function

# as.factor(feature_column) changes feature to factor(categorical)
# as.integer(feature_column) changes feature to integer type
# lets say that we want to change cylinders column to qualitative variable

typeof(cylinders)               # before modifying the type it is "double"

?factor                         # Encodes a vector as factor(also known as category),similar to groupby

cylinders = as.factor(cylinders)

typeof(cylinders)               # now the type is integer but it is factorised ,type ?factor for details

plot(cylinders,mpg)             # Notice how the plot has been changed,previously it
                                #      is scatter plot,now it is box plot
                                # If the plot(x,y) has x as categorical it will give box plot as output

plot(cylinders,mpg,col="red")   # Adds red color to the boxes inside the plot

plot(cylinders,mpg,col="red",
     varwidth = T)                # Shrinks the boxes inside box plot respective to the variance

plot(cylinders,mpg,col="red",     # Rotates the plot to view the boxes horizontally,previously
                                  #    they are vertical,Also "T" can be used instead of "TRUE" anywhere
     varwidth=T,horizontal=T)

plot(cylinders,mpg,col="red",     # Adding labels to the plot ,xlab="xlabel here",ylab="ylabel here"
     varwidth=T,horizontal=T,
     xlab="number of cylinder",
     ylab="Miles per Gallon")

# Histograms for each feature column can also be plotted in R

hist(mpg)                                   # Histogramns are just graphical representation of each
                                            #   values occurence in a bar type plots,total sum of
                                            #   all occurences = total number of rows in that feature

hist(mpg,col = "red",breaks = 15)           # we can add extra arguments as well,col="some color name"
                                            #   ,breaks=15
                                            # breaks says that lets take max and min value and
                                            #   break it into 15 item sets,equally spaced and
                                            #   calculate frequency for each set

hist(cylinders)                             # We cannot plot histogram for non numeric values,here
                                            # cylinders is factor and therefore it cannot be plotted

hist(as.integer(cylinders))                 # we can use as.integer() to convert cylinders to integer
                                            #   and then plot
                                            # Remember as.integer(feature) will not change feature
                                            #   itself ,it has to be assigned to a new one

hist(cylinders)                             # See the cylinders type itself is not changed ,but
                                            #   as.integer() returns a feature array which are integers

# We will learn another function pairs() which creates scatterplot matrix
# i.e. a scatter plot for every pair of variables for any given data set
?pairs

pairs(Auto_data_csv)                        # pairs(list or dataframe), Cool,isn't it?

pairs(~mpg+displacement+horsepower          # If we want to have scatter plot between selected few
                                            #   features,we can use this way
      +weight+acceleration)

# Identify() function is a useful interactive method for identifying value for a paritcular
#     variable for points on plot.

plot(horsepower,mpg)

identify(horsepower,mpg,name)               # After printing the plot we call identify with 3 arguments,
                                            #   x axis,yaxis and the value we like to see in
                                            #   interactive mode
                                            # has to press "esc" after finishing picking the
                                            #   points form the plot to exit the interactive
                                            #   mode (This is on Windows)

# Finally summary() function to see the summary of a data object

?summary
summary(Auto_data_csv)                      # gives data such as Min,Max,Mean,Median,1st Qu,3rd Qu
                                            # 1st quartile -- Means 25% of observations are below
                                            #      this quantity(approx)
                                            # 3rd quartile means 75% of observations are below
                                            #      this quantity(approx)
                                            # for qualitative variables such as name it will
                                            #      list no. of observations that will fall in
                                            #      each category

summary(horsepower)                         # we can also select single feature too

# we can use savehistory() and loadhistory() to save the commands we typed and load them later

savehistory()

loadhistory()


