######### Introduction to R #########

# c() is used to concentate whatever is present inside the brackets
# seperated by comma

x <- c(1,3,3,4)   # <- is assignment operator assigning the right side one to left side variable

y=c(1,2,3,4)      # = is also same as <- ,wtf why do people use <- then??

length(x)         # gives a length of a vector ,single dimension vector

length(y)

ls()               # this function is used to list all the objects that we have saved in workspace so far

rm(x,y)            # rm deletes the variables that we have saved,have to specify inside what to delete

ls()               # Notice that x,y no longer appear

rm(list = ls())    # ls() creates a list of all loaded variables and we assign it to variable list ,then we ask 
                   # rm() to remove everything that is saved
                   # The command listed deletes every variable loaded


########## Matrix ##############

?matrix            # ?function_name is used to see help for that particular function

# lets create a simple matrix
# matrix takes 3 arguments, first is the data itself as a single vector,second is number of rows ,third is number of columns
# here z will be = [[1,3],[2,4]] each column is generated first and data is appended columnwise
z=matrix(data= c(1,3,2,4),nrow = 2,ncol = 2)

z

# matrix function can also be written as below,without specifying argument names,but the order has to be maintained
z_1 = matrix(c(1,3,2,4),2,2)        

z_1

# matrix function has another argument byrow=TRUE which means we populate the matrix literally by rows instead of going by columns
# here z will be generated by rows instead of columns as given above
z_2= matrix(c(1,3,2,4),2,2,byrow = TRUE)

z_2

########## Some Vectorized Implementation ##########

sqrt(z)               # often these functions operates on each element in a matrix or vector or dataframe,no need to use for loop to iterate over

z^2                   # squares every element in a matrix or vector

?rnorm

rnorm(4)              # rnorm creates a random vector or normal variables with given size defaults= (mean=0 and standard deviation = 1)

rnorm(5,mean=0,sd=4)  # here we are explicitly specifying mean and stadard deviation for the vector to be created

# sometimes we want our code to reproduce the exact same set of random numbers
# we can use set.seed() function to do this

?set.seed

# lets set the seed to some integer
set.seed(1303)

y=rnorm(5)

mean(y)                # to get the mean of a vector y

mean(z_1)              # mean works on matrices too but it gives mean for all the elements present in the matrix

var(y)                 # to get the variance of a vector

var(z_1)               # gives a matrix containing variance for each column say matrix=[[1,2],[3,4]] variance will return [[2,2],[2,2]]

sd(y)                  # standard deviation of a vector y

sd(z_1)                # returns a value over a matrix,same as mean function,it unwraps all elements in matrix in to single vector and computes for that.



################# Plotting #################

# plot() function is the primary way to plot data in R
# plot(x,y) produces a scatter plot of numbers in x versus numbers in y

# lets initialize x and y and lets plot..

x_forplot = rnorm(100)
y_forplot = rnorm(100)

# basic plot command
plot(x_forplot,y_forplot)

# we can also add arguments for labelling on axis as well as main plot title
plot(x_forplot,y_forplot,xlab = "Xaxis Label here",ylab = "Yaxis Label here",main = "Main title label here")

# we also want to save the plots ,the following commands will help in saving in different file formats
pdf("Plotted_figure.pdf")                 # to save in pdf format

jpeg("Plotted_figure.jpeg")

# After initializing the export command to pdf or jpeg then the plot has to called
# it will not take the plots that are already present in the workspace

plot(x_forplot,y_forplot,col="green")

# this following command will say to R that we are done with plot and it can save
# Remember until and unless you initialize this command you cannot acces plot function and whatever you are trying to save will not be saved.It will say 0 kb file
dev.off()
























